{% set name = "cuda-cupti" %}
{% set version = "12.8.90" %}
{% set lib_version = "2025.1.1" %}
{% set cuda_version = "12.8" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-ppc64le" %}  # [ppc64le]
{% set platform = "linux-sbsa" %}  # [aarch64]
{% set platform = "windows-x86_64" %}  # [win]
{% set target_name = "x86_64-linux" %}  # [linux64]
{% set target_name = "ppc64le-linux" %}  # [ppc64le]
{% set target_name = "sbsa-linux" %}  # [aarch64]
{% set target_name = "x64" %}  # [win]
{% set extension = "tar.xz" %}  # [not win]
{% set extension = "zip" %}  # [win]

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_cupti/{{ platform }}/cuda_cupti-{{ platform }}-{{ version }}-archive.{{ extension }}
  sha256: 7bf5db86cb82f26a6a3cb9e2fa4dc2a131d25885f59fdbc647938929924405db  # [linux64]
  sha256: bf7640a559f53a9c19b3f42443da20ef4cb1c28cacf00d5506ee7dcf7e1e6a45  # [aarch64]
  sha256: 8a09eab5412addc6e132a55bac41ebad0141de3b5b6f6eca3028eb9e49a8cdb6  # [win]

build:
  number: 1
  binary_relocation: false
  skip: true  # [osx or ppc64le]

requirements:
  build:
    - cf-nvidia-tools 1.*
    - patchelf <0.18.0  # [linux]

outputs:
  - name: cuda-cupti
    files:
      - lib/libcupti*.so.*                    # [linux]
      - targets/{{ target_name }}/lib/*.so.*  # [linux]
      - Library\bin\checkpoint.dll            # [win]
      - Library\bin\cupti*.dll                # [win]
      - Library\bin\nvperf*.dll               # [win]
      - Library\bin\pcsamplingutil.dll        # [win]
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - {{ stdlib("c") }}
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
      host:
        - cuda-version {{ cuda_version }}
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
      run_constrained:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
    test:
      requires:
        - patchelf  # [linux]
      files:
        - test-rpath.sh
      commands:
        - test -L $PREFIX/lib/libcupti.so.{{ version.split(".")[0] }}                            # [linux]
        - test -L $PREFIX/lib/libcupti.so.{{ lib_version }}                                      # [linux]
        - test -L $PREFIX/targets/{{ target_name }}/lib/libcupti.so.{{ version.split(".")[0] }}  # [linux]
        - test -f $PREFIX/targets/{{ target_name }}/lib/libcupti.so.{{ lib_version }}            # [linux]
        - bash test-rpath.sh                                                                     # [linux]
        - if not exist %LIBRARY_BIN%\checkpoint.dll exit 1                 # [win]
        - if not exist %LIBRARY_BIN%\cupti64_{{ lib_version }}.dll exit 1  # [win]
        - if not exist %LIBRARY_BIN%\nvperf_host.dll exit 1                # [win]
        - if not exist %LIBRARY_BIN%\nvperf_target.dll exit 1              # [win]
        - if not exist %LIBRARY_BIN%\pcsamplingutil.dll exit 1             # [win]
    about:
      home: https://developer.nvidia.com/cuda-toolkit
      license_file: LICENSE
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: Provides libraries to enable third party tools using GPU profiling APIs.
      description: |
        Provides libraries to enable third party tools using GPU profiling APIs.
      doc_url: https://docs.nvidia.com/cuda/cupti/index.html

  - name: cuda-cupti-dev
    build:
      run_exports:
        - {{ pin_subpackage("cuda-cupti", max_pin="x") }}
    files:
      - lib/checkpoint.so                         # [linux]
      - lib/libcupti.so                           # [linux]
      - lib/libnv*.so                             # [linux]
      - lib/libpcsamplingutil.so                  # [linux]
      - targets/{{ target_name }}/lib/*.so        # [linux]
      - targets/{{ target_name }}/include         # [linux]
      - Library\include                           # [win]
      - Library\lib\*.lib                         # [win]
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - {{ stdlib("c") }}
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
      host:
        - cuda-version {{ cuda_version }}
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
        - {{ pin_subpackage("cuda-cupti", exact=True) }}
      run_constrained:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
        - cuda-cupti-static >={{ version }}
    test:
      commands:
        - test -L $PREFIX/lib/libcupti.so                                    # [linux]
        - test -L $PREFIX/lib/libnvperf_host.so                              # [linux]
        - test -L $PREFIX/lib/libnvperf_target.so                            # [linux]
        - test -f $PREFIX/targets/{{ target_name }}/include/cupti.h          # [linux]
        - test -L $PREFIX/targets/{{ target_name }}/lib/libcupti.so          # [linux]
        - test -f $PREFIX/targets/{{ target_name }}/lib/libnvperf_host.so    # [linux]
        - test -f $PREFIX/targets/{{ target_name }}/lib/libnvperf_target.so  # [linux]
        - if not exist %LIBRARY_LIB%\cupti.lib exit 1                        # [win]
        - if not exist %LIBRARY_INC%\cupti.h exit 1                          # [win]
    about:
      home: https://developer.nvidia.com/cuda-toolkit
      license_file: LICENSE
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: Provides libraries to enable third party tools using GPU profiling APIs.
      description: |
        Provides libraries to enable third party tools using GPU profiling APIs.
      doc_url: https://docs.nvidia.com/cuda/cupti/index.html

  - name: cuda-cupti-static
    build:
      skip: true  # [not linux64]
    files:
      - targets/{{ target_name }}/lib/*static.a
    requirements:
      build:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
      host:
        - cuda-version {{ cuda_version }}
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
      run_constrained:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
    test:
      commands:
        - test -f $PREFIX/targets/{{ target_name }}/lib/libcupti_static.a  # [linux]
    about:
      home: https://developer.nvidia.com/cuda-toolkit
      license_file: LICENSE
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: Provides libraries to enable third party tools using GPU profiling APIs.
      description: |
        Provides libraries to enable third party tools using GPU profiling APIs.
      doc_url: https://docs.nvidia.com/cuda/cupti/index.html

  - name: cuda-cupti-doc
    files:
      - targets/{{ target_name }}/{{ name }}/samples
      - targets/{{ target_name }}/{{ name }}/doc
    requirements:
      build:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
      host:
        - cuda-version {{ cuda_version }}
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
      run_constrained:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
    test:
      commands:
        - test -d $PREFIX/targets/{{ target_name }}/{{ name }}/samples  # [linux]
        - test -d $PREFIX/targets/{{ target_name }}/{{ name }}/doc      # [linux]
    about:
      home: https://developer.nvidia.com/cuda-toolkit
      license_file: LICENSE
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: Provides libraries to enable third party tools using GPU profiling APIs.
      description: |
        Provides libraries to enable third party tools using GPU profiling APIs.
      doc_url: https://docs.nvidia.com/cuda/cupti/index.html

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: Provides libraries to enable third party tools using GPU profiling APIs.
  description: |
    Provides libraries to enable third party tools using GPU profiling APIs.
  doc_url: https://docs.nvidia.com/cuda/cupti/index.html

extra:
  feedstock-name: cuda-cupti
  recipe-maintainers:
    - conda-forge/cuda
